name: Horusec IaC Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  horusec-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Horusec CLI
        run: |
          curl -fsSL https://github.com/ZupIT/horusec/releases/latest/download/horusec_linux_amd64 -o horusec
          chmod +x horusec
          sudo mv horusec /usr/local/bin/

      - name: Run Horusec scan (Docker Disabled)
        run: |
          horusec start \
            -p ./ \
            --config-file-path="./horusec-config.json" \
            -e="true" \
            -o="json" \
            --json-output-file="horusec-results.json" \
            -D
